name: pharmacy_inventory_platform
description: Offline-first inventory and POS platform for small pharmacies.
publish_to: 'none'
version: 1.3.4+5

environment:
  sdk: '>=3.4.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: any
  flutter_riverpod: ^2.5.1
  drift: ^2.20.2
  sqlite3_flutter_libs: ^0.5.24
  path_provider: ^2.1.4
  path: ^1.9.0
  bcrypt: ^1.1.3
  excel: ^4.0.3
  mobile_scanner: ^5.2.3
  googleapis_auth: ^1.6.0
  http: ^1.2.1
  csv: ^6.0.0
  google_sign_in: ^6.2.1
  pdf: ^3.11.1
  printing: ^5.13.3
  fl_chart: ^0.69.2
  image_picker: ^1.1.2
  shared_preferences: ^2.3.2
  package_info_plus: ^8.0.0
  file_picker: ^8.1.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  build_runner: ^2.4.11
  drift_dev: ^2.20.2

flutter:
  generate: true
  uses-material-design: true
  assets:
    - assets/data/indonesian_drugs.csv
    - assets/branding/app_icon.png
